var quotes = [
  "To, co mogę robić w moim życiu to nie oznacza tego, co mogę robić.",
  "Zwracaj się do mnie po imieniu kurwa do mnie Mirosław, a nie kurwa Szrek.",
  "Dziękuję bardzo z okazji dzień chłopaka kochana jesteś i naprawdę szczerze ci współczuje.",
  "Kurwierzalna sprawa, trzeba powiedzieć a to trzeba powiedzieć b.",
  "Chłopie kupisz starter za 5zł będziesz miał internet, gibagajty.",
  "Kochani, szanowni państwo, zepsułam komputer niestety, ale bez komputera się obejdzie, łaski bez, do widzenia.",
  "Powiem wam, że u mnie jest trochę ciężko, ale u mnie nie jest tak ciężko, ja właśnie odchudzam się, droga jest pusta, wolny, można iść, ale słuchajcie trzeba troszeczkę z umiarem.",
  "I zobaczysz będziesz miał konsefekcje, będziesz miał, ja mówię do ciebie.",
  "Stawiam na PiS, bo Prawo i Sprawiedliwość też mają w sobie poczucie.",
  "Donald Tusk, on wszystko zrobił, aby dostarczyć węgiel do Rosji.",
  "Jeżeli macie odebrane świadectwo moi kochani to dziękujemy bardzo, z paskiem czy bez słuchajcie, to nie ma zielonego znaczenia, ja też odebrałem świadectwo i to bez paska moi kochani.",
  "Słuchaj, ja poszłam wczoraj na stadion, a ten kolega zatrzymał się i zapytał, gdzie mogę jechać na wieżowiec, tam proszę jechać od granicy.",
  "Słuchajcie, ja powiem krótko… powiem krótko… żeby ja umarła na pogrzebie to żeby nie doszło do awantury, jeżeli żeby doszło do awantury na pogrzebie, to proszę was szanujcie się nawzajem tego człowieka.",
  "Życie jest za krótki, losom za krótki a dupa szeroki.",
  "Cierp człowieku, cierp, a szukaj zbawienie… i to na zawsze.",
  "Świat nie wierzy w zoo, szkoda naszych łez.",
  "Bo dziewczyny są pijany i są pod wpływem alkoholu, rozumiecie czy nie? Jeżeli tak, to wy jesteście psychiczny dziewczyny.",
  "Nie ma życia na takiego społeczeństwa, na tym świecie wszyscy znają, cała Polska.",
  "Ten syn ma Auschwitz",
  "A na co jesteś chory? Na muchomory. Prosze zrozumiec to na własne oczy. Prosze zrozumieć z całego serca",
  "Pierwsza zasada moi kochani - nie ufaj zajomych, których nie znasz.",
  "Coś mnie serce ugutowało jak gorący wodzie kąpany.",
  "Pokazałem gołą dupę za pieniądze",
  "Ja już raz byłem w więzieniu i dostałem jako doywocie. Taki będzie głupi żart.",
  "Nie mam humoru moi kochani, a jeżeli mam humor to mogę wam dosłownio 😀 jeden uśmiech poprawić. No i na dobrą sprawę ja już mam jebać takich hejterów.",
  "Jest takie przysłowie - Marność za marnościami a tylko jeden jest jedna marność. Jan Egarzka Egzakra Święta Izraela. Amen.",
  "Jak zapłacisz za telewizor? Jak płacisz za abonament radiowo telewizyjny? Słuchajcie, idzie tak drogo, że idzie ciut ciut.",
  "A wiecie ile kosztuje inflacja? A paliwo? A na żarcie? Nic jak goły i wesoły, jak mysz kościelna.",
  "Uwaga, wskazówka - nigdy nie zostawiaj dziecko w samochodzie, departura może być 30 stopni a dziecko powoduje umieranie podgrzaniu.",
  "Nigdy nie zostawiaj dziecka w samochodzie, bo może być jeszcze gorzej udału albo zawał. Starszych ludzi kobiet i mężczyzny warto ostrzegać.",
  "Pozdrawiam serdecznie jakiś osrany menel czy coś takiego.",
  "A będę prezydentem! Będę! Będę startował Andrzej Duda.",
  "A ja chodzę na randkę? NIE! Słuchaj, po pierwsze nie mam dziewczyny ale po drugie będę miał, po trzecie muszę dokładnie poukładać i się dogadać.",
  "A grzmoty, a trzaskanie było. Nie pytajcie się.",
  "Proszę zrozumieć z całego serca. W imię Ojca i Syna i Ducha Świętego. Proszę was o to.",
  "Stoi pociąg na stacji, na długim poronie.",
  "Prawda jest taka, że zaczynam troszeczkę niepokoić się z tym, co się wydarzyło.",
  "Słuchacie, ja jestem doświadczony, doświączony naukowiec. W życiu trzeba zostać biznesnenem. To jest szołbiznes, Warszawa. Tu żyję, tu zarabiają.",
  "Załóżmy jak twoja matka, twój ojciec podaje osobiste dowód czy co to słuchacie, tu nie ma zmiłuj się nad nami.",
  "0 + 0 to będzie 5",
  "Jeżeli jajko zaniesie do wielkanocy to kiedy prędzej czy później przyjdzie zajączek po ciebie.",
  "5 + 4 to będzie 1400 równa się 1400.",
  "Kiedy mądrość spada. Kiedy hejterów stanie się po oczy, a stanie się twoja zasługa. Tak mówię przysłowie. Kiedy głupie hejterzy są to hejterzy zostaje nikim.",
  "Zaszkodzić nam może, chroń nas dobry Boże.",
  "Słuchacie, po raz ostani mówie. Idzie wysoki ceny. Błagam was, wy lepiej nie kupujcie. Jeżeli będziecie kupować smartfony za tak ekstra taniej albo drogo to słuchajcie, nie bierzcie pod uwagę.",
  "Cudze walicie swego nie znacie.",
  "Wy jesteście nienormalni. Na całym świecie, cała Polska już macie psychoaltyka, łeb nie tyka. Już macie świstak w głowie.",
  "Ale dzisiaj będzie parzyć, jak skurwesyn.",
  "Jest taki przysłowie, piniądze nie rosną na drzewach, pieniądze nie rosną na drzewach, a piniądze z tego srają",
]
