var quotes = [
  "To, co mogę robić w moim życiu to nie oznacza tego, co mogę robić.",
  "Zwracaj się do mnie po imieniu kurwa do mnie Mirosław, a nie kurwa Szrek.",
  "Dziękuję bardzo z okazji dzień chłopaka kochana jesteś i naprawdę szczerze ci współczuje.",
  "Kurwierzalna sprawa, trzeba powiedzieć a to trzeba powiedzieć b.",
  "Chłopie kupisz starter za 5zł będziesz miał internet, gibagajty.",
  "Kochani, szanowni państwo, zepsułam komputer niestety, ale bez komputera się obejdzie, łaski bez, do widzenia.",
  "Powiem wam, że u mnie jest trochę ciężko, ale u mnie nie jest tak ciężko, ja właśnie odchudzam się, droga jest pusta, wolny, można iść, ale słuchajcie trzeba troszeczkę z umiarem.",
  "I zobaczysz będziesz miał konsefekcje, będziesz miał, ja mówię do ciebie.",
  "Stawiam na PiS, bo Prawo i Sprawiedliwość też mają w sobie poczucie.",
  "Donald Tusk, on wszystko zrobił, aby dostarczyć węgiel do Rosji.",
  "Jeżeli macie odebrane świadectwo moi kochani to dziękujemy bardzo, z paskiem czy bez słuchajcie, to nie ma zielonego znaczenia, ja też odebrałem świadectwo i to bez paska moi kochani.",
  "Słuchaj, ja poszłam wczoraj na stadion, a ten kolega zatrzymał się i zapytał, gdzie mogę jechać na wieżowiec, tam proszę jechać od granicy.",
  "Słuchajcie, ja powiem krótko… powiem krótko… żeby ja umarła na pogrzebie to żeby nie doszło do awantury, jeżeli żeby doszło do awantury na pogrzebie, to proszę was szanujcie się nawzajem tego człowieka.",
  "Życie jest za krótki, losom za krótki a dupa szeroki.",
  "Cierp człowieku, cierp, a szukaj zbawienie… i to na zawsze.",
  "Świat nie wierzy w zoo, szkoda naszych łez.",
  "Bo dziewczyny są pijany i są pod wpływem alkoholu, rozumiecie czy nie? Jeżeli tak, to wy jesteście psychiczny dziewczyny.",
  "Nie ma życia na takiego społeczeństwa, na tym świecie wszyscy znają, cała Polska.",
  "Ten syn ma Auschwitz",
]
